export const COMUNAS_POR_REGION = {
  'Arica y Parinacota': [
    'Arica', 'Camarones', 'Putre', 'General Lagos',
  ],
  'Tarapacá': [
    'Iquique', 'Alto Hospicio', 'Pozo Almonte', 'Camiña',
    'Colchane', 'Huara', 'Pica',
  ],
  'Antofagasta': [
    'Antofagasta', 'Mejillones', 'Sierra Gorda', 'Taltal',
    'Calama', 'Ollagüe', 'San Pedro de Atacama',
    'Tocopilla', 'María Elena',
  ],
  'Atacama': [
    'Copiapó', 'Caldera', 'Tierra Amarilla',
    'Chañaral', 'Diego de Almagro',
    'Vallenar', 'Alto del Carmen', 'Freirina', 'Huasco',
  ],
  'Coquimbo': [
    'La Serena', 'Coquimbo', 'Andacollo', 'La Higuera', 'Paihuano', 'Vicuña',
    'Illapel', 'Canela', 'Los Vilos', 'Salamanca',
    'Ovalle', 'Combarbalá', 'Monte Patria', 'Punitaqui', 'Río Hurtado',
  ],
  'Valparaíso': [
    'Valparaíso', 'Viña del Mar', 'Concón', 'Quilpué', 'Villa Alemana',
    'Casablanca', 'Juan Fernández', 'Puchuncaví', 'Quintero',
    'Los Andes', 'Calle Larga', 'Rinconada', 'San Esteban',
    'La Ligua', 'Cabildo', 'Papudo', 'Petorca', 'Zapallar',
    'Quillota', 'La Calera', 'Hijuelas', 'La Cruz', 'Nogales',
    'San Antonio', 'Algarrobo', 'Cartagena', 'El Quisco', 'El Tabo', 'Santo Domingo',
    'San Felipe', 'Catemu', 'Llaillay', 'Panquehue', 'Putaendo', 'Santa María',
    'Limache', 'Olmué', 'Isla de Pascua',
  ],
  'Metropolitana de Santiago': [
    'Santiago', 'Providencia', 'Las Condes', 'Ñuñoa', 'La Florida',
    'Maipú', 'Pudahuel', 'Puente Alto', 'La Reina', 'Vitacura',
    'Lo Barnechea', 'Peñalolén', 'San Miguel', 'Macul', 'La Granja',
    'San Joaquín', 'Lo Espejo', 'La Cisterna', 'El Bosque', 'La Pintana',
    'Pedro Aguirre Cerda', 'San Ramón', 'Cerrillos', 'Cerro Navia',
    'Conchalí', 'Estación Central', 'Huechuraba', 'Independencia',
    'Lo Prado', 'Quilicura', 'Quinta Normal', 'Recoleta', 'Renca',
    'Colina', 'Lampa', 'Tiltil',
    'San Bernardo', 'Buin', 'Calera de Tango', 'Paine',
    'Pirque', 'San José de Maipo',
    'Melipilla', 'Alhué', 'Curacaví', 'María Pinto', 'San Pedro',
    'Talagante', 'El Monte', 'Isla de Maipo', 'Padre Hurtado', 'Peñaflor',
  ],
  "O'Higgins": [
    'Rancagua', 'Codegua', 'Coinco', 'Coltauco', 'Doñihue', 'Graneros',
    'Las Cabras', 'Machalí', 'Malloa', 'Mostazal', 'Olivar', 'Peumo',
    'Pichidegua', 'Quinta de Tilcoco', 'Rengo', 'Requínoa', 'San Vicente',
    'Pichilemu', 'La Estrella', 'Litueche', 'Marchihue', 'Navidad', 'Paredones',
    'San Fernando', 'Chépica', 'Chimbarongo', 'Lolol', 'Nancagua',
    'Palmilla', 'Peralillo', 'Placilla', 'Pumanque', 'Santa Cruz',
  ],
  'Maule': [
    'Talca', 'Constitución', 'Curepto', 'Empedrado', 'Maule', 'Pelarco',
    'Pencahue', 'Río Claro', 'San Clemente', 'San Rafael',
    'Cauquenes', 'Chanco', 'Pelluhue',
    'Curicó', 'Hualañé', 'Licantén', 'Molina', 'Rauco', 'Romeral',
    'Sagrada Familia', 'Teno', 'Vichuquén',
    'Linares', 'Colbún', 'Longaví', 'Parral', 'Retiro',
    'San Javier', 'Villa Alegre', 'Yerbas Buenas',
  ],
  'Ñuble': [
    'Chillán', 'Bulnes', 'Chillán Viejo', 'El Carmen', 'Pemuco',
    'Pinto', 'Quillón', 'San Ignacio', 'Yungay',
    'Coihueco', 'Ñiquén', 'San Carlos', 'San Fabián', 'San Nicolás',
    'Cobquecura', 'Coelemu', 'Ninhue', 'Portezuelo', 'Quirihue', 'Ránquil', 'Treguaco',
  ],
  'Biobío': [
    'Concepción', 'Coronel', 'Chiguayante', 'Florida', 'Hualqui',
    'Lota', 'Penco', 'San Pedro de la Paz', 'Santa Juana',
    'Talcahuano', 'Tomé', 'Hualpén',
    'Lebu', 'Arauco', 'Cañete', 'Contulmo', 'Curanilahue', 'Los Álamos', 'Tirúa',
    'Los Ángeles', 'Antuco', 'Cabrero', 'Laja', 'Mulchén', 'Nacimiento',
    'Negrete', 'Quilaco', 'Quilleco', 'San Rosendo', 'Santa Bárbara',
    'Tucapel', 'Yumbel', 'Alto Biobío',
  ],
  'La Araucanía': [
    'Temuco', 'Carahue', 'Cunco', 'Curarrehue', 'Freire', 'Galvarino',
    'Gorbea', 'Lautaro', 'Loncoche', 'Melipeuco', 'Nueva Imperial',
    'Padre Las Casas', 'Perquenco', 'Pitrufquén', 'Pucón', 'Saavedra',
    'Teodoro Schmidt', 'Toltén', 'Vilcún', 'Villarrica', 'Cholchol',
    'Angol', 'Collipulli', 'Curacautín', 'Ercilla', 'Lonquimay',
    'Los Sauces', 'Lumaco', 'Purén', 'Renaico', 'Traiguén', 'Victoria',
  ],
  'Los Ríos': [
    'Valdivia', 'Corral', 'Futrono', 'La Unión', 'Lago Ranco',
    'Lanco', 'Los Lagos', 'Máfil', 'Mariquina', 'Paillaco',
    'Panguipulli', 'Río Bueno',
  ],
  'Los Lagos': [
    'Puerto Montt', 'Calbuco', 'Cochamó', 'Fresia', 'Frutillar',
    'Los Muermos', 'Llanquihue', 'Maullín', 'Puerto Varas',
    'Castro', 'Ancud', 'Chonchi', 'Curaco de Vélez', 'Dalcahue',
    'Puqueldón', 'Queilén', 'Quellón', 'Quemchi', 'Quinchao',
    'Osorno', 'Puerto Octay', 'Purranque', 'Puyehue',
    'Río Negro', 'San Juan de la Costa', 'San Pablo',
    'Chaitén', 'Futaleufú', 'Hualaihué', 'Palena',
  ],
  'Aysén': [
    'Coyhaique', 'Lago Verde', 'Aysén', 'Cisnes', 'Guaitecas',
    'Cochrane', 'O\'Higgins', 'Tortel', 'Chile Chico', 'Río Ibáñez',
  ],
  'Magallanes': [
    'Punta Arenas', 'Laguna Blanca', 'Río Verde', 'San Gregorio',
    'Cabo de Hornos', 'Antártica', 'Porvenir', 'Primavera', 'Timaukel',
    'Puerto Natales', 'Torres del Paine',
  ],
  'Todo Chile (online)': [],
};
